package ar.com.pagofacil.batch.model;

public enum TipoRegistroError {
	ERROR_REGISTRO_VENDEDOR, ERROR_REGISTRO_COMPRADOR, ERROR_REGISTRO_MAILS, 
	ERROR_REGISTRO_COMPROBANTE, ERROR_REGISTRO_DETALLE, ERROR_REGISTRO_IMPUESTO
}
